export const PLATFORM_CHANGED = 'PLATFORM_CHANGED';

export const UDPATE_ITEM_ARRAY = 'UDPATE_ITEM_ARRAY';
export const UDPATE_ITEM = 'UDPATE_ITEM';

export const ITEM_SELECTED_INDEX = 'ITEM_SELECTED_INDEX';
export const TAB_SELECTED = 'TAB_SELECTED';
export const ADD_ANIMATION = 'ADD_ANIMATION';
export const COMPONENT_ADD = 'COMPONENT_ADD';
export const FILE_DOWNLAOD = 'FILE_DOWNLOAD';
export const FILE_DOWNLAODED = 'FILE_DOWNLOADED';

export const HOVER_HANDLER = 'HOVER_HANDLER'; 
export const SHOW_PREVIEW = 'SHOW_PREVIEW';
export const CLEAR_ARRAY = 'CLEAR_ARRAY';
export const FILE_UPLOADED = 'FILE_UPLOADED';
export const FILE_LOADED = 'FILE_LOADED';
export const PRODUCT_CHANGED = 'PRODUCT_CHANGED';
